name: Hello World Workflow

on:
  push:
    branches:
      - main
    workflow_dispatch:  # Adds a manual run button in the Actions tab



env:
  ENV_NAME: QA

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World with environment
        run: echo "Hello World \"$ENV_NAME\""
