name: Hello World Workflow

on:
  workflow_dispatch:  # Manual trigger

jobs:
  say-hello:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env_name: [QA, DEV, PROD]

    env:
      ENV_NAME: ${{ matrix.env_name }}

    steps:
      - name: Print Hello World with environment
        run: echo "Hello World \"$ENV_NAME\""
